spring:
  application:
    name: stubborn-stub-runner

server:
  port: 8083

stubrunner:
  ids:
    - sh.stubborn:stubborn-broker:+:stubs:8083
  stubs-mode: LOCAL

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
