apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stubborn-broker
  namespace: argocd
  labels:
    app.kubernetes.io/name: stubborn-broker
    app.kubernetes.io/part-of: stubborn-broker
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:marcingrzejszczak/stubborn-broker.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: broker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
