apiVersion: v1
kind: ServiceAccount
metadata:
  name: stubborn-broker
  labels:
    app.kubernetes.io/name: stubborn-broker
    app.kubernetes.io/part-of: stubborn-broker
automountServiceAccountToken: false
