/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sh.stubborn.oss.publisher;

import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.contract.stubrunner.StubFinder;
import org.springframework.cloud.contract.stubrunner.spring.AutoConfigureStubRunner;
import org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Tests {@link BrokerPublisher} using stubs from the broker's stubs JAR via Spring Cloud
 * Contract Stub Runner. No manual WireMock stubs — all stubs are generated by the
 * broker's contract tests ({@code @Tag("generate-stubs")}).
 */
@SpringBootTest(classes = BrokerPublisherTest.TestApp.class, webEnvironment = SpringBootTest.WebEnvironment.NONE)
@AutoConfigureStubRunner(ids = "sh.stubborn:stubborn-broker:+:stubs", stubsMode = StubRunnerProperties.StubsMode.LOCAL)
class BrokerPublisherTest {

	@SpringBootApplication
	static class TestApp {

	}

	@Autowired
	StubFinder stubFinder;

	@Test
	void should_publish_contracts_when_broker_returns_201(@TempDir Path tempDir) throws IOException {
		// given — contract file matching the publish-contract stub
		Files.writeString(tempDir.resolve("create-order.yaml"), "request: {}");
		URL brokerUrl = this.stubFinder.findStubUrl("stubborn-broker");
		BrokerPublisher publisher = BrokerPublisher.create(brokerUrl.toString(), "admin", "admin");

		// when
		PublishSummary summary = publisher.publish("order-service", "1.0.0", tempDir, "Manages orders",
				"team-commerce");

		// then
		assertThat(summary.appResult()).isEqualTo(PublishResult.CREATED);
		assertThat(summary.publishedCount()).isEqualTo(1);
		assertThat(summary.skippedCount()).isZero();
		assertThat(summary.contractNames()).containsExactly("create-order");
	}

	@Test
	void should_skip_existing_contracts_when_broker_returns_409(@TempDir Path tempDir) throws IOException {
		// given — data matching the 409 conflict stubs
		Files.writeString(tempDir.resolve("existing-contract.yaml"), "request: {}");
		URL brokerUrl = this.stubFinder.findStubUrl("stubborn-broker");
		BrokerPublisher publisher = BrokerPublisher.create(brokerUrl.toString(), "admin", "admin");

		// when
		PublishSummary summary = publisher.publish("existing-service", "1.0.0", tempDir, "Manages orders",
				"team-commerce");

		// then
		assertThat(summary.appResult()).isEqualTo(PublishResult.ALREADY_EXISTS);
		assertThat(summary.publishedCount()).isZero();
		assertThat(summary.skippedCount()).isEqualTo(1);
	}

	@Test
	void should_throw_authentication_exception_when_broker_returns_401(@TempDir Path tempDir) throws IOException {
		// given — data matching the 401 unauthorized stub
		Files.writeString(tempDir.resolve("get-order.yaml"), "request: {}");
		URL brokerUrl = this.stubFinder.findStubUrl("stubborn-broker");
		BrokerPublisher publisher = BrokerPublisher.create(brokerUrl.toString(), "bad", "creds");

		// when / then
		assertThatThrownBy(
				() -> publisher.publish("unauthenticated-service", "1.0.0", tempDir, "Manages orders", "team-commerce"))
			.isInstanceOf(BrokerAuthenticationException.class);
	}

	@Test
	void should_return_empty_summary_when_directory_is_empty(@TempDir Path tempDir) {
		// given — empty directory, registration still happens
		URL brokerUrl = this.stubFinder.findStubUrl("stubborn-broker");
		BrokerPublisher publisher = BrokerPublisher.create(brokerUrl.toString(), "admin", "admin");

		// when
		PublishSummary summary = publisher.publish("order-service", "1.0.0", tempDir, "Manages orders",
				"team-commerce");

		// then
		assertThat(summary.appResult()).isEqualTo(PublishResult.CREATED);
		assertThat(summary.publishedCount()).isZero();
		assertThat(summary.skippedCount()).isZero();
		assertThat(summary.contractNames()).isEmpty();
	}

	@Test
	void should_return_empty_summary_when_directory_does_not_exist() {
		// given — non-existent directory
		URL brokerUrl = this.stubFinder.findStubUrl("stubborn-broker");
		BrokerPublisher publisher = BrokerPublisher.create(brokerUrl.toString(), "admin", "admin");

		// when
		PublishSummary summary = publisher.publish("order-service", "1.0.0", Path.of("/nonexistent/path"),
				"Manages orders", "team-commerce");

		// then
		assertThat(summary.appResult()).isEqualTo(PublishResult.CREATED);
		assertThat(summary.publishedCount()).isZero();
		assertThat(summary.contractNames()).isEmpty();
	}

	@Test
	void should_throw_connection_exception_when_broker_unreachable(@TempDir Path tempDir) throws IOException {
		// given — unreachable broker URL (no WireMock stubs needed)
		Files.writeString(tempDir.resolve("get-order.yaml"), "request: {}");
		BrokerPublisher publisher = BrokerPublisher.create("http://localhost:1", "admin", "admin");

		// when / then
		assertThatThrownBy(
				() -> publisher.publish("order-service", "1.0.0", tempDir, "Manages orders", "team-commerce"))
			.isInstanceOf(BrokerConnectionException.class);
	}

}
