{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stubborn-broker.fullname" . }}
  labels:
    {{- include "stubborn-broker.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.postgresql.username | b64enc | quote }}
  db-password: {{ .Values.postgresql.password | b64enc | quote }}
{{- end }}
